permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "ArtBox"
  description: |
    A platform that focuses on helping art-lovers find the next piece to decorate their walls, while giving a space for artists to sell their art and reach a larger audience.
  font_url: "https://fonts.googleapis.com/css?family=PT+Sans:400,700|PT+Serif:400,700,700i&display=swap"
  colors:
    background: "--color-secondary"
    accent: "--color-primary"
  rationales:
    typefaces.primary: |
      PT Serif was selected because it is a nice, simple and easy to read font. PT Serif is to be used for all body copy only and for link hover.
    typefaces.secondary: |
      PT Sans was selected because it pairs well with the primary typeface. PT Sans is to be used for all other instances.
    colors.primary: |
      The primary colour is a variant of black. It was selected to be simple and clean. Should be used for text.
    colors.secondary: |
      The secondary colour is to balance with the primary colour. Is to be used for backgrounds.
    colors.accent: |
      The accent colour is bright and colourful. It's purpose is to stand out as a pop of colour to create some contrast. Is to be used for very few instances, hover colour on links, buttons, citations.
