title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to action for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      The basic button meant for banners to draw attention.

  ghost:
    title: "Ghost"
    description: |
      The ghost button is for small instances.

  light:
    title: "Light"
    description: |
      The light button is used only for the navigation.
